To insert element in existing array
utkarsh-shekhar/basic-programs pull request #113
Opened 2020-10-03 11:37 UTC by Skm26

Added program to insert element into an existing array

2020-10-03 16:50 UTC, utkarsh-shekhar requested changes

2020-10-03 16:50 UTC, utkarsh-shekhar commented on java/Insert_array.java
> +
Please remove excess lines.

2020-10-03 16:50 UTC, utkarsh-shekhar commented on java/Insert_array.java
> +		{
Please format the code.

If the IDE you use doesn't support that, it's time to get one that does. ;)
You can also use online tools for formatting code, like: [https://codebeautify.org/javaviewer](https://codebeautify.org/javaviewer)

2020-10-03 16:50 UTC, utkarsh-shekhar commented
Also, the file name should either be snake case or camel case or Pascal case.

2020-10-06 04:24 UTC, Skm26 reviewed
Changes Done

2020-10-06 04:25 UTC, Skm26 commented
Have done the Changes,Please do add the hacktober fest tag.
Thank you

On Sat, Oct 3, 2020 at 10:20 PM Utkarsh Shekhar <notifications@github.com>
wrote:

> *@utkarsh-shekhar* requested changes on this pull request.
> ------------------------------
>
> In java/Insert_array.java
> <https://github.com/utkarsh-shekhar/basic-programs/pull/113#discussion_r499163250>
> :
>
> > +	x=s.nextInt();
> +
> +	for(int i=(n-1);i>=(pos-1);i--)
> +	{
> +	a[i+1]=a[i];
> +	}
> +	a[pos-1]=x;
> +	System.out.print("After inserting:");
> +	for(int i=0;i<n;i++)
> +	{
> +	System.out.print(a[i]+",");
> +	}
> +	System.out.println(a[n]);
> +}
> +}
> +
>
> Please remove excess lines.
> ------------------------------
>
> In java/Insert_array.java
> <https://github.com/utkarsh-shekhar/basic-programs/pull/113#discussion_r499163397>
> :
>
> > @@ -0,0 +1,42 @@
> +import java.util.Scanner;
> +public class Insertarray
> +{
> +	public static void main(String[] args)
> +	{
> +	int n,pos,x;
> +	Scanner s=new Scanner(System.in);
> +	System.out.println("Enter no of elements you want in array:");
> +	n=s.nextInt();
> +	int a[]=new int[n+1];
> +	System.out.println("Enter alll the elements:");
> +	for(int i=0;i<n;i++)
> +		{
>
> Please format the code.
>
> If the IDE you use doesn't support that, it's time to get one that does. ;)
> You can also use online tools for formatting code, like:
> https://codebeautify.org/javaviewer
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/utkarsh-shekhar/basic-programs/pull/113#pullrequestreview-501558864>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARHCTND3EJOVFM26TKLUBMLSI5I4LANCNFSM4SCTKCBQ>
> .
>

2020-10-06 08:52 UTC, utkarsh-shekhar approved these changes
Nice work!

2020-10-06 08:52 UTC, merged